### ISSUE TITLE
Turn on Travis CI for this repo

### ISSUE THREAD

**Issue by cclauss** [nodejs/tap2junit#13]
Manually kick off the first build on master at https://travis-ci.com/nodejs/tap2junit

**Comment by sam-github** [comment]
@cclauss What is it you need done?

**Comment by sam-github** [comment]
@nodejs/build @mhdawson Who has sufficient privileges in Travis to add this repo to it so it can be built? I don't, I tried, and have a lot of access on github side, but not on the Travis side.

**Comment by mhdawson** [comment]
I think I can do this.  Opening https://github.com/nodejs/build/issues/1924 as an FYI to build WG.

**Comment by mhdawson** [comment]
@rsam for future reference I think you could have enabled it here: https://github.com/organizations/nodejs/settings/installations

select `Configure` for Travis CI and then add the project as one that it is enabled for.

**Comment by cclauss** [comment]
Thanks Michael.  The Travis builds are now running at https://travis-ci.com/nodejs/tap2junit

**Comment by mhdawson** [comment]
:)
