### ISSUE TITLE
Is tap2junit incompatible with zos?

### ISSUE THREAD

**Issue by cclauss** [nodejs/tap2junit#16]
# @TODO(mhdawson): get tap2junit working on zOS

https://github.com/nodejs/build/blob/master/ansible/roles/jenkins-worker/tasks/main.yml#L113

**Comment by sam-github** [comment]
Community Node.js doesn't CI or support z/os, but I think it is under development.

@miladfar might know whether this is really an issue.

**Comment by mhdawson** [comment]
We already run test on z/OS for libuv https://ci.nodejs.org/view/libuv/job/libuv-test-commit-zos/. If that uses tap2junit it would be a short term issue.  Other than that we'll have to fix that at part of getting our z/OS patches upstreamed which won't be in the short term as we first have to upstream our patches for v8.

**Comment by richardlau** [comment]
libuv-test-commit-* jobs do not use tap2junit on any platform.

**Comment by richardlau** [comment]
tap2junit appears to be working on z/OS. I've removed the comment from the ansible script (and am installing tap2junit on z/OS) in https://github.com/nodejs/build/pull/2505.
