### ISSUE TITLE
Add @rajcze as an Owner in PyPI account

### ISSUE THREAD

**Issue by cclauss** [nodejs/tap2junit#17]
@rajcze If you create an account on pypi.org, we can make you an Owner so that you can publish new releases that can be pip installed.

**Comment by rajcze** [comment]
I'm not sure I follow - new releases for which project? This one? I mean, I could, but I don't see the need, honestly (I might miss something). I wanted to offer the same for the pytap13 package on pip, honestly :)

**Comment by rvagg** [comment]
probably better not be liberal with this @cclauss, as a trusted part of our test infra it gives access to a large amount of servers by the fact that it's invoked on every test run
