### ISSUE TITLE
Can't parse tap file

### ISSUE THREAD

**Issue by gdams** [nodejs/tap2junit#2]
I am trying to parse a tap file with the tap plan at the end instead of at the start. It does not appear to be working though. Here is my tap plan:
```
TAP version 13
ok 1 - test
  ---
  # This test passed
  duration_ms: 5000
  ...
1..1
```

This works if I move the plan to the start.
It also works I edit the parser to change `seek_test = True` but I cannot imagine that this would be an appropriate fix

**Comment by jbergstroem** [comment]
What's going on here is that the tap13 parser I'm using is looking for the plan and then parses tests it finds below that line. Not great. I chose the parser based on avoiding including a long list of dependencies seeing how this will have to run on platforms that even lacks setuptools.

I'll look at improving it, but I won't have much time to work on this until the holidays.

**Comment by fmartinsons** [comment]
Hello with the master, there is no issue parsing the test plan @gdams showed, here is the xml produced
```
<?xml version="1.0" encoding="utf-8"?>
<testsuites disabled="0" errors="0" failures="0" tests="1" time="5000.0">
	<testsuite disabled="0" errors="0" failures="0" name="test" skipped="0" tests="1" time="5000" hostname="SGX-CMP-776">
		<testcase name="- test" time="5000.000000"/>
	</testsuite>
</testsuites>
```

**Comment by cclauss** [comment]
@gdams Is this still an issue in the current code?

**Comment by gdams** [comment]
No I think this can be closed now
