### ISSUE TITLE
add publishing credentials to repo secrets

### ISSUE THREAD

**Issue by MoLow** [nodejs/tap2junit#56]
since this repo is under the node.js org - there should be a way for @nodejs/build to publish a new version.
that can be done either by adding a repository secret and a GitHub actions flow to publish a version or by adding credentials to https://github.com/nodejs-private/secrets

**Comment by MoLow** [comment]
added to the https://github.com/nodejs/tap2junit/labels/tsc-agenda so we can discuss - this and https://github.com/nodejs/tap2junit/pull/54 seem stuck with only a single individual having credentials to release this.
@mhdawson - I am not sure if this repo is part of the automation to be added to TSC meetings, so lets make sure it is added manually if not

**Comment by mhdawson** [comment]
@MoLow the tool looks across the org so as long as it is under nodejs.org it should appear on the agenda.

**Comment by legendecas** [comment]
Using OCID provided by GitHub Action, we don't have to save credentials or secrets to publish pypi packages, like how [gyp-next](https://github.com/nodejs/gyp-next/blob/main/.github/workflows/release-please.yml) is published. As a nodejs account is created in https://github.com/nodejs/admin/issues/863, I believe this can move forward and untag https://github.com/nodejs/tap2junit/labels/tsc-agenda?

**Comment by benjamingr** [comment]
@MoLow should this be discussed or is @legendecas 's suggestion sufficient?
