### ISSUE TITLE
Transfer to nodejs/build?

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/tap2junit#8]
Hi Johan, would you consider moving tap2junit to the nodejs organization?

I was looking at a couple of tap2junit failures on Node's CI but realized that I can't really make changes because there is no way to publish a new version.

**Comment by jbergstroem** [comment]
> Hi Johan, would you consider moving tap2junit to the nodejs organization?

Sorry. Been on vacation. Sure - lets get it done.

**Comment by cclauss** [comment]
Bump on this one.  #5 seems to be blocking the Python 3 progress at https://github.com/nodejs/node/pull/29451#issuecomment-533727436

**Comment by sam-github** [comment]
@bnoordhuis do you have a pypi account? @trott @mhdawson @rvagg -- we use this, but to maintain it we'd need pypi accounts to publish it to -- or we could just vendor it into node perhaps?

Its copyright status and code heritage is not clear to me, if that matters. Only one file has a copyright statement, and it's GPL, by Redhat.

**Comment by cclauss** [comment]
I am willing to do the PyPI mechanics and be responsible for the repo but does the TSC need to weigh in on creating the new repo especially given the copyright  question?

**Comment by Trott** [comment]
> I am willing to do the PyPI mechanics and be responsible for the repo but does the TSC need to weigh in on creating the new repo especially given the copyright question?

The policy for transferring a repo into the nodejs org is at https://github.com/nodejs/admin/blob/4f463ad194a48a7d73c1d94588903539819fcbe2/GITHUB_ORG_MANGEMENT_POLICY.md#repositories. In a nutshell: open an issue in the admin repository, wait 72 hours, transfer it in if no one opposes doing so.

**Comment by cclauss** [comment]
Done at nodejs/admin#413

**Comment by cclauss** [comment]
> Who should I add to pypi? Couldn't find your username

Please add __cclauss__

**Comment by sam-github** [comment]
@jbergstroem On node.js side we have to wait about 2 more days to accept the repo, but if you could add pypi credentials for `cclauss` and initiate the xfer, I think that will allow us to press the "accept the  transfer" button in a couple days. Thanks!

**Comment by jbergstroem** [comment]
@sam-github will do.

Edit:
- [x] added `cclauss` as owner of `tap2junit` on pypi
- [x] transferred ownership of this repo to `@nodejs/build` team

**Comment by cclauss** [comment]
👍 I got a notice that I have been added as Owner to the PyPI project tap2junit by jbergstroem.

**Comment by sam-github** [comment]
@cclauss Great, @jbergstroem thanks!
